config/routes.rb
Rails.application.routes.draw do

  get 'json' => 'listings#json'
  get '/index' => 'listings#index'
  get '/show' => 'listings#show'
  root 'listings#show'

end

app/models/Listing.rb
class Listing
  attr_accessor :listing_class, :price, :address, :url, :unit
    def initialize(input)
      @listing_class = input[:listing_class]
      @price= input[:price]
      @address= input[:address]
      @url= input[:url]
      @unit= input[:unit]
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def index
    parser = ListingParser.new()
    @listings = parser.parse_listings
  end

  def show

  end

  def json
    parser = ListingParser.new()
    @listings = parser.parse_listings
    render json: @listings
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StreetEasySnooper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/listings/index.html.erb
<div align="center" ><%= button_to "Gimme The JSON!", json_path, method: "get" %></div>

<ol class="rounded-list">
<% @listings.each do |listing, index| %>
<li><br><p>
Address: <%= listing.address %><br>
Unit: <%= listing.unit %><br>
Price: <%= number_to_currency(listing.price) %><br>
Type of Listing: <%= listing.listing_class %><br>
<%= link_to("Find Out More Here", listing.url )%> <br> 
<br></p>
</li>
<% end %>
</ol>

app/views/listings/show.html.erb
<div align="center" >
<%= button_to "Gimme Some Listings!", index_path, method: "get" %>
</div>